### ISSUE TITLE
Problem using deferred with custom completion token

### ISSUE THREAD

**Issue by 4e4o** [chriskohlhoff/asio#1150]
I am using custom timed token described in [this](https://cppalliance.org/richard/2021/10/10/RichardsOctoberUpdate.html) article. It works fine with aiso <= 1.22.0. But with last 1.24.0 i'v got template compilation error. Problem arises [here](https://github.com/4e4o/boost_base/blob/master/src/Timed/Timed.hpp#L142) when Op=deffered_async_operation. With version 1.22.0 at [this](https://github.com/4e4o/boost_base/blob/master/src/Timed/Timed.hpp#L142) line [this](https://github.com/chriskohlhoff/asio/blob/asio-1-22-0/asio/include/asio/experimental/deferred.hpp#L210) non const operator called and everything perfect. But in 1.24.0 [this](https://github.com/chriskohlhoff/asio/blob/asio-1-24-0/asio/include/asio/deferred.hpp#L235) const operator with const & ref qualifier is called and i don't know why. Wrapped operation is mutable lambda, i don't know how to correctly tell deffered_async_operation to use non const overload with rvalue q-ref. Need help.
