### ISSUE TITLE
Compile Error Boost 1.81 beta

### ISSUE THREAD

**Issue by pbondo** [chriskohlhoff/asio#1163]
The following code is compiling fine and presumable working as expected in boost asio 1.80, however it fails to compile in 1.81 Beta with quite a long error list (attached)

#include<boost/asio.hpp>
#include<boost/asio/experimental/coro.hpp>
#include<boost/asio/experimental/use_coro.hpp>

using namespace boost::asio;

experimental::coro<int> my_coroutine(ip::tcp::socket my_socket)
{
   char data[100];
   std::size_t n = co_await my_socket.async_read_some(buffer(data), experimental::use_coro);
   co_yield n;
}

g++-11 -std=c++20 -I/opt/boost/1.81.0/include  boost_issue.cpp

The use case is being able to return some value from a coroutine.

[boost_issue.log](https://github.com/chriskohlhoff/asio/files/10075741/boost_issue.log)

**Comment by klemens-morgenstern** [comment]
You need to  specify signature & return type of `coro`, the above should've never worked.

**Comment by pbondo** [comment]
Edited. Sorry formatting lost "int" part.

`experimental::coro<int> my_coroutine(ip::tcp::socket my_socket)`

**Comment by klemens-morgenstern** [comment]
Weird, what happens `coro<int, void>` ?

**Comment by airaou** [comment]
I fixed this compilation error. It appeared to be caused by `R(asio::error_code)` on line 98 of include/asio/experimental/impl/use_coro.hpp. Changing it to `R(std::exception_ptr)` resolved the compilation issue.

```cpp
template <typename Allocator, typename R>
struct async_result<
    experimental::use_coro_t<Allocator>, R(std::exception_ptr)>
{
  template <typename Initiation, typename... InitArgs>
  static auto initiate_impl(Initiation initiation,
      std::allocator_arg_t, Allocator, InitArgs... args)
    -> experimental::coro<void(), void,
      asio::associated_executor_t<Initiation>, Allocator>
  {
    co_await deferred_async_operation<
      R(asio::error_code) /* <- here */, Initiation, InitArgs...>(
        deferred_init_tag{}, std::move(initiation), std::move(args)...);
  }
```
