### ISSUE TITLE
as_default_on fails with any_io_executor in Boost.ASIO 1.76

### ISSUE THREAD

**Issue by gummif** [chriskohlhoff/asio#813]
This fails in 1.76, but works in 1.75. Works fine with explicit `io_context::executor`. Using gcc 10.2, C++17.

```c++
using sock = boost::asio::detached_t::as_default_on_t<boost::asio::basic_stream_socket<boost::asio::ip::tcp>>;
boost::asio::io_context ctx;
sock s{ctx.get_executor()};
```

```
a long error...
boost_1_76_0/boost/asio/execution/context_as.hpp:75:23: error: incomplete type ‘boost::asio::execution::is_executor<boost::asio::detached_t::executor_with_default<boost::asio::any_io_executor> >’ used in nested name specifier
   75 |       is_executor<U>::value
      |                       ^~~~~
/home/gummi/boost/boost_1_76_0/boost/asio/detail/config.hpp:254:27: note: in definition of macro ‘BOOST_ASIO_STATIC_CONSTEXPR’
  254 |     static constexpr type assignment
      |                           ^~~~~~~~~~
/home/gummi/boost/boost_1_76_0/boost/asio/execution/context_as.hpp:80:20: error: incomplete type ‘boost::asio::execution::is_executor<boost::asio::detached_t::executor_with_default<boost::asio::any_io_executor> >’ used in nested name specifier
   80 |           >::type::value
      |                    ^~~~~
/home/gummi/boost/boost_1_76_0/boost/asio/detail/config.hpp:254:27: note: in definition of macro ‘BOOST_ASIO_STATIC_CONSTEXPR’
  254 |     static constexpr type assignment
      |                           ^~~~~~~~~~
/home/gummi/boost/boost_1_76_0/boost/asio/execution/context_as.hpp:85:20: error: incomplete type ‘boost::asio::execution::is_executor<boost::asio::detached_t::executor_with_default<boost::asio::any_io_executor> >’ used in nested name specifier
   85 |           >::type::value));
      |                    ^~~~~
/home/gummi/boost/boost_1_76_0/boost/asio/detail/config.hpp:254:27: note: in definition of macro ‘BOOST_ASIO_STATIC_CONSTEXPR’
  254 |     static constexpr type assignment
      |                           ^~~~~~~~~~
and more...
```
