### ISSUE TITLE
Don't inject type traits into public interfaces

### ISSUE THREAD

**Issue by vinniefalco** [chriskohlhoff/asio#259]
`<boost/asio/detail/type_traits.hpp>` injects symbols like `integral_constant` into a public namespace (`boost::asio::`). I believe this is a bad practice. For example, the following program fails to compile under Visual Studio:
```
#include <boost/type_traits.hpp>
#include <boost/asio.hpp>
#include <memory>
namespace boost {
void foo()
{
    using namespace boost::asio;
    boost::is_final<std::allocator<char>>{};
}
} // boost
```

Error message:
```
1>C:\Users\vinnie\src\boost\boost/type_traits/is_final.hpp(25): error C2872: 'integral_constant': ambiguous symbol
1>C:\Users\vinnie\src\boost\boost/type_traits/integral_constant.hpp(53): note: could be 'boost::integral_constant'
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include\xtr1common(24): note: or       'std::integral_constant'
1>C:\Users\vinnie\src\boost\libs\beast\test\beast\websocket\utf8_checker.cpp(9): note: see reference to class template instantiation 'boost::is_final<std::allocator<char>>' being compiled
1>C:\Users\vinnie\src\boost\boost/type_traits/is_final.hpp(25): error C2872: 'integral_constant': ambiguous symbol
1>C:\Users\vinnie\src\boost\boost/type_traits/integral_constant.hpp(53): note: could be 'boost::integral_constant'
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\include\xtr1common(24): note: or       'std::integral_constant'
1>Done building project "tests-beast-websocket.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

Removing the `using namespace boost::asio;` resolves the error. However, users should be able to have using directives which don't create name conflicts.
