### ISSUE TITLE
Backward compatibility broken in 1.13.0

### ISSUE THREAD

**Issue by vagran** [chriskohlhoff/asio#395]
The following code was successfully compiled in 1.12.2 and does not compile in 1.13.0:  

```
            asio::ip::udp::socket socket;
            ....
            auto executor = socket.get_executor();
            socket.shutdown(asio::ip::udp::socket::shutdown_type::shutdown_both);
            socket = asio::ip::udp::socket(executor.context());
```

```
asio/detail/io_object_impl.hpp:61:40: error: no member named 'get_executor' in 'asio::execution_context'
      implementation_executor_(context.get_executor(),
                               ~~~~~~~ ^
asio/basic_socket.hpp:131:7: note: in instantiation of function template specialization 'asio::detail::io_object_impl<asio::detail::reactive_socket_service<asio::ip::udp>, asio::executor>::io_object_impl<asio::execution_context>' requested here
    : impl_(context)
      ^
asio/basic_datagram_socket.hpp:106:7: note: in instantiation of function template specialization 'asio::basic_socket<asio::ip::udp, asio::executor>::basic_socket<asio::execution_context>' requested here
    : basic_socket<Protocol, Executor>(context)
      ^
ssdp.h:109:22: note: in instantiation of function template specialization 'asio::basic_datagram_socket<asio::ip::udp, asio::executor>::basic_datagram_socket<asio::execution_context>' requested here
            socket = asio::ip::udp::socket(executor.context());
```

**Comment by tstenner** [comment]
This is expected, see [the release notes](https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/history.html#boost_asio.history.asio_1_14_0___boost_1_70):

```
Note: One potential source of breakage in existing user code is when reusing an I/O object's io_context for constructing another I/O object, as in:

    asio::steady_timer my_timer(my_socket.get_executor().context());

To fix this, either construct the second I/O object using the first I/O object's executor:

    asio::steady_timer my_timer(my_socket.get_executor());

or otherwise explicitly pass the io_context:

    asio::steady_timer my_timer(my_io_context);
```
