### ISSUE TITLE
Issue with execute in 1.29

### ISSUE THREAD

**Issue by diehard2** [chriskohlhoff/asio#1417]
This worked in 1.28.x and is failing in 1.29. Reduced to simplest reproducer for brevity

#include "asio.hpp"  // NOLINT

 error: ‘execute’ is not a member of ‘asio::execution’

```
#include "asio.hpp"  // NOLINT
struct DummyExecutor {
    template<typename F>
    void execute(F&&) const {};
};

void foo() 
{
  asio::execution::execute(DummyExecutor{}, []() mutable {
  });
}

```

**Comment by justend29** [comment]
@diehard2 `execute` was deprecated and recently removed. The [documentation](https://www.boost.org/doc/libs/1_82_0/doc/html/boost_asio/reference/execution__execute.html) indicates to use the member function instead.
