### ISSUE TITLE
support sendmmsg and recvmmsg

### ISSUE THREAD

**Issue by zkas** [chriskohlhoff/asio#1062]
is there an plan to support sendmmsg and recvmmsg on unix platform? or WSARecvMsg on windows platform?we need "sendmmsg" or "recvmmsg" to realize
aggregate sending and receiving data through udp socket

**Comment by virgiliofornazin** [comment]
I'm finalizing a patch that does this and support it on Linux, QNX, (Open/Free/Net)BSD, AIX (and all that supports it).
I'll proposing a primary patch release with this implementations in next days, that will need some work (adapt to < c++11, 'boostify' some parts, etc).

**Comment by panicgh** [comment]
Any update to this? sendmmsg/recvmmsg would really be a nice feature for some applications.

**Comment by virgiliofornazin** [comment]
I have the sources working on my github asio fork, in a branch.

Chris told this is not becoming the final interface in asio since need reworking done to support final asio release.

Its working on bsd / apple (i/mac)osx and linux.

**Comment by virgiliofornazin** [comment]
https://github.com/virgiliofornazin/asio/tree/feature/multiple_datagram_buffers_sequence-io-sendmmsg-recvmmsg

**Comment by markyang59** [comment]
Could you show an example code with async_send?
I need this feature REALLY !.

**Comment by markyang59** [comment]
This feature is great. 
Why it is not included latest boost (1.85) ?
and Why it is marked as 'Stale'

**Comment by markyang59** [comment]
> You can currently use async_receive with null_buffers and then recvmmsg yourself inside the handler. I'm not sure how you might do something similar with async_send.
> 
> I look forward to a patch which implements this without workarounds like mine.

How did you do with workaround ?
Could you give me a tip ??
I am trying to async_send with sendmmsg

**Comment by virgiliofornazin** [comment]
asio::resizeable_multiple_buffer_sequence<asio::mutable_buffer,
asio::ip::tcp::endpoint> buffer_sequences;
std::vector<std::vector<uint8_t>> buffer_vector;

buffer_vector.push_back(std::vector<uint8_t>{});
auto& buffer = buffer_vector.at(0);

buffer.resize(1500);
asio::mutable_buffer asio_buffer(std::addressof(buffer.at(0)),
buffer.size());
buffer_sequences.push_back(converted_buffer);

auto callback = [this](std::error_code const& error_code, size_t const
bytes_transferred, size_t const operations_executed) mutable
        {
            // reenqueue_operations_pending(payloads);

            // handle_send_multiple(error_code, bytes_transferred,
operations_executed, payloads);
        };
socket->async_send_multiple_buffer_sequence(buffer_sequences, callback);

**Comment by virgiliofornazin** [comment]
This interface is not optimal. I did it in a project I work and for my
case, works perfectly because of allocation strategies and socket
implementation. It must be reworked or serve as inspiration for a final
implementation. Feel free to fork my project.

**Comment by markyang59** [comment]
Thank you very much for your kind reply.
I tried the example code. but got errors ..here is my test code
```
std::vector<uint8_t> bv0(1400);
std::vector<uint8_t> bv1(1400);
std::vector<uint8_t> bv2(1400);
ba::mutable_buffer buf0(bv0.data(), bv0.size());
ba::mutable_buffer buf1(bv1.data(), bv1.size());
ba::mutable_buffer buf2(bv2.data(), bv2.size());
ba::resizeable_multiple_buffer_sequence<ba::mutable_buffer, ba::ip::udp::endpoint> bufs;
bufs.push_back(buf0);
bufs.push_back(buf1);
bufs.push_back(buf2);
		
sock.async_send_multiple_buffer_sequence(bufs,
	[](std::error_code const& ec, size_t const byteio, size_t const ops) mutable
	{
		cout<<"Completion : ec:"<<ec.value()<<"  msg:"<<ec.message() << "  "
			<<"byteio:"<<byteio<<"  ops:"<<ops<<endl;
	 });
```

But Got 2 kinds of errors

```
Completion : ec:55  msg:No buffer space available  byteio:0  ops:0
Completion : ec:0  msg:Undefined error: 0  byteio:0  ops:3
```

What did I do wrong ??
ba::ip::udp::endpoint  is wrong parameter ?

**Comment by markyang59** [comment]
Thank you for your reply.
But I have a question. below is an example code.
```
while (1)
{
  auto bufs = new ba::resizeable_multiple_buffer_sequence<ba::mutable_buffer, ba::ip::udp::endpoint>;
  std::vector<uint8_t> bv0(1400);
  bufs->push_back(ba::mutable_buffer((PBYTE)bv0.data(), bv0.size()));
			
  auto callback = [bufs](boost::system::error_code ec, size_t byteio, size_t ops) mutable
  {
	cout << "Completion : ec:"<<ec.value()
             <<"  msg:"<<ec.message() << "  "
	     <<"byteio:"<<byteio<<"  ops:"<<ops<<endl;

	delete bufs;
						
	if(ec.value()==55) sleep_ms(100); // MUST
  };
  sock.async_send_multiple_buffer_sequence(*bufs, callback);
}
```

For each IO call. I made muti_buffer_seq and deleted it in the completion handler.
This code works very short time and crashes. with segmentation fault
Is this usage wrong?
Could you show me an example that sends dynamically new packets and cleans up in the completion handler?

**Comment by virgiliofornazin** [comment]
I will look into this and get back to you.

**Comment by markyang59** [comment]
Thank you very much. This feature will save my project!
and one more thing.
The above sample code keeps increasing memory usage..slowly but steadily.
(1 buffer crashed immediately, I tested with 2 buffers)

**Comment by markyang59** [comment]
Sorry to bother you.
I changed  basic_datagram_socket.hpp:752 like below and seems fixed..
but not sure. Could you check this ?
```
//if (multiple_buffer_sequence.adjusted_count() > 1)
if (multiple_buffer_sequence.adjusted_count() > 0)
{
```

**Comment by virgiliofornazin** [comment]
Ok, I'll check it out.

**Comment by virgiliofornazin** [comment]
I know it makes a difference, but I didn`t need to implement it yet to
support my demands.
It changes a lot the way buffers are handled and I think it should be
another implementation
because the way it's done.

**Comment by markyang59** [comment]
Thank you for your kind reply..really
I have one question. below is the situation.
1. make  multiple_buffer_sequence which holds 100 buffers
2. send only 10 buffers in it from the start

multiple_buffer_sequence_view seems to support a similar function.
but it skips front buffers and uses them after that.
I want to send front 10 buffers

**Comment by markyang59** [comment]
Thanks to your great library I almost solved problems..Thank you.
Just one question.
For Windows..How can I do this multi-packet send job ?
With RIO ?
or
WSASetUdpSendMessageSize ?

**Comment by virgiliofornazin** [comment]
RIO implementation needs a lot of redesign to make it work.

I never looked at WSASetUdpSendMessageLike.

**Comment by markyang59** [comment]
Dear.

```
sock.async_receive_multiple_buffer_sequence(bufseq, comp);
```
bufseq size is 256 for receive.
but it seems this call completion as soon as any number of packet receive - even 1 packet
Could I make to wait until many packets received and call completion at that time ?

**Comment by markyang59** [comment]
Could you show me example for receive ?

**Comment by nolange** [comment]
Since the "full" support is not ready apparently, I would appreciate if the low-level socket_ops parts could get merged on its own.

**Comment by FaiqueAli** [comment]
Hi I am trying to impliment restinio using QNX qcc compiler, which has dependency on asio. now I am getting various issue for example "undefined reference to `sendmsg'" , "undefined reference to `recv'" etc.
does these issue poping up due to these expecting changes?
if yes, when is it expected to be available?

**Comment by virgiliofornazin** [comment]
i did not tested it on qnx. apple os'es, linux and windows.
maybe qnx / bsd need some fixups.

**Comment by FaiqueAli** [comment]
So I have searched out for solutions and found [this](https://github.com/chriskohlhoff/asio/issues/1422) PR related to `QNX` with `asio`, may be this is the fix for which I am looking for.
Could you please consider [this](https://github.com/chriskohlhoff/asio/issues/1422) PR and if it validates the criteria for merge. so that, It will become easier for me to proceed.
thanks :)

**Comment by utoni** [comment]
Long time no activity. Any updates on this? It would be great to have `recvmmsg` and `sendmmsg` support within Boost. 🐱

**Comment by markyang59** [comment]
Is there any update yet ?
It seems this patch don't work with boost 1.93
So I stick to 1.88 just for this patch.
Please update this patch working with latest boost.
