### ISSUE TITLE
Build error on macOS 10.13

### ISSUE THREAD

**Issue by AJenbo** [chriskohlhoff/asio#836]
a41c0b5299115264d2740ae0f19fb88e6124d90d
```
/Users/runner/work/devilutionX/devilutionX/build/_deps/asio-src/asio/include/asio/detail/memory.hpp:85:12: error: aligned allocation function of type 'void *(std::size_t, std::align_val_t)' is only available on macOS 10.14 or newer
  return ::operator new(size, std::align_val_t(align));
```
https://github.com/diasurgical/devilutionX/runs/2752941770

https://github.com/chriskohlhoff/asio/blame/f18dc1dcb3c72fa98b5f01f142038c9075ccd045/asio/include/asio/detail/memory.hpp#L85

Looks like it was probably caused by https://github.com/chriskohlhoff/asio/commit/64d595a8fbbb7ef72f5892b17fe2105a2fe12b95

Is there a way we can still build this on older platforms by setting a flag?

Known working commit: 77bcfe775ad63178942c9dd95d93edd10442b80f

**Comment by chriskohlhoff** [comment]
This is fixed on master.
